version: "3.8"

services:
  ncat:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - storage:/var/www/html/storage/app
      - logs:/var/www/html/storage/logs
    ports:
      - "8081:80"
    restart: unless-stopped

volumes:
  storage:
    driver: local
  logs:
    driver: local
